font:
  normal:
    family: JuliaMono Nerd Font
    style: Regular

  bold:
    family: JuliaMono Nerd Font
    style: Medium

  italic:
    family: JuliaMono Nerd Font
    style: Italic

  bold_italic:
    family: JuliaMono Nerd Font
    style: Bold Italic

  size: 16
  offset:
    x: 0
    y: 0


key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }


window:
  opacity: 0.95

  title: Alacritty
schemes:
  ### Doom One ###
  DoomOne: &DoomOne
    primary:
      background: '#0E1012'
      foreground: '#bbc2cf'
    bright:
      blue:    '#3071db'
colors: *DoomOne
